export default {
    SEARCH_INPUT_CHANGE: 'SEARCH_INPUT_CHANGE',
    SET_USERS_LIST: 'SET_USERS_LIST',
    ADD_TO_USERS_LIST: 'ADD_TO_USERS_LIST',
    EMPTY_USERS_LIST: 'EMPTY_USERS_LIST',
    SET_LIST_PAGE: 'SET_LIST_PAGE',
    SET_USER_DETAIL: 'SET_USER_DETAIL',
    HANDLE_WELLCOME_CHANGE:'HANDLE_WELLCOME_CHANGE',
    HANDLE_VISBLE :'HANDLE_VISBLE',
}